language: node_js
node_js: 
  - 10.16
cache: npm

# before install:
# install:

# before_script: 
script:
  # - node server/server.js
  - npm test

# after_success:
# after_failure:
# before deploy:
# deploy:
# after deploy:
#services: 