language: node_js
node_js: 
  - 10.16
cache: npm

# before install:
# install:

# before_script: 
script:
  - npm run server_dev
  - node server/server.js

# after_success:
# after_failure:
# before deploy:
# deploy:
# after deploy: